#!/bin/bash

cp $HOME/.zshrc ..
cp $HOME/.vars.sh ..
cp $HOME/.bashrc ..
cp $HOME/.zprofile ..
cp $HOME/.bash_profile ..
cp $HOME/.profile ..
cp $HOME/.xinitrc ..
cp $HOME/.config/lvim/config.lua ..
cp $HOME/.tmux.conf ..
cp $HOME/.aliases.sh ..
cp -r $HOME/.config/kitty/ ..
cp -r $HOME/.config/tilix/ ..
cp -r $HOME/.config/nvim/ ..
cp $HOME/.config/i3/config ..
cp $HOME/.p10k.zsh ..
